// <auto-generated />
using System;
using GS2_Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GS2_Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GS2_Domain.Entities.Conteudo", b =>
                {
                    b.Property<int>("ConteudoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("conteudo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConteudoId"));

                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("TipoConteudoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_conteudo_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("ConteudoId");

                    b.HasIndex("CursoId");

                    b.HasIndex("TipoConteudoId");

                    b.ToTable("conteudo", (string)null);
                });

            modelBuilder.Entity("GS2_Domain.Entities.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CursoId"));

                    b.Property<int>("CargaHorariaHrs")
                        .HasColumnType("integer")
                        .HasColumnName("carga_horaria_hrs");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<int>("NivelId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_id");

                    b.Property<int>("ProprietarioId")
                        .HasColumnType("integer")
                        .HasColumnName("proprietario_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("character varying(130)")
                        .HasColumnName("titulo");

                    b.Property<int?>("TrilhaAprendizagemId")
                        .HasColumnType("integer")
                        .HasColumnName("trilha_aprendizagem_id");

                    b.HasKey("CursoId");

                    b.HasIndex("NivelId");

                    b.HasIndex("ProprietarioId");

                    b.HasIndex("TrilhaAprendizagemId");

                    b.ToTable("cursos", (string)null);
                });

            modelBuilder.Entity("GS2_Domain.Entities.CursoPalavraChave", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<int>("PalavraChaveId")
                        .HasColumnType("integer")
                        .HasColumnName("palavra_chave_id");

                    b.HasKey("CursoId", "PalavraChaveId");

                    b.HasIndex("PalavraChaveId");

                    b.ToTable("curso_palavra_chave", (string)null);
                });

            modelBuilder.Entity("GS2_Domain.Entities.MeusCursos", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.HasKey("UsuarioId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("meus_cursos", (string)null);
                });

            modelBuilder.Entity("GS2_Domain.Entities.Nivel", b =>
                {
                    b.Property<int>("NivelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nivel_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NivelId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("NivelId");

                    b.ToTable("nivel", (string)null);

                    b.HasData(
                        new
                        {
                            NivelId = 1,
                            Descricao = "Junior"
                        },
                        new
                        {
                            NivelId = 2,
                            Descricao = "Pleno"
                        },
                        new
                        {
                            NivelId = 3,
                            Descricao = "Senior"
                        });
                });

            modelBuilder.Entity("GS2_Domain.Entities.PalavrasChaves", b =>
                {
                    b.Property<int>("PalavraChaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("palavra_chave_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PalavraChaveId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("PalavraChaveId");

                    b.ToTable("palavras_chaves", (string)null);
                });

            modelBuilder.Entity("GS2_Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("refresh_token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("replaced_by_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("GS2_Domain.Entities.TipoConteudo", b =>
                {
                    b.Property<int>("TipoConteudoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipo_conteudo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoConteudoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("TipoConteudoId");

                    b.ToTable("tipo_conteudo", (string)null);

                    b.HasData(
                        new
                        {
                            TipoConteudoId = 1,
                            Descricao = "Textos e Documentos"
                        },
                        new
                        {
                            TipoConteudoId = 2,
                            Descricao = "Videoaulas"
                        },
                        new
                        {
                            TipoConteudoId = 3,
                            Descricao = "Áudios e Podcasts"
                        });
                });

            modelBuilder.Entity("GS2_Domain.Entities.TipoUsuario", b =>
                {
                    b.Property<int>("TipoUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipo_usuario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoUsuarioId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cargo");

                    b.HasKey("TipoUsuarioId");

                    b.ToTable("tipo_usuario", (string)null);

                    b.HasData(
                        new
                        {
                            TipoUsuarioId = 1,
                            Descricao = "Administrador"
                        },
                        new
                        {
                            TipoUsuarioId = 2,
                            Descricao = "Cliente"
                        },
                        new
                        {
                            TipoUsuarioId = 3,
                            Descricao = "Instrutor"
                        });
                });

            modelBuilder.Entity("GS2_Domain.Entities.TrilhaAprendizagem", b =>
                {
                    b.Property<int>("TrilhaAprendizagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("trilha_aprendizagem_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrilhaAprendizagemId"));

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("integer")
                        .HasColumnName("carga_horaria_hrs");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.HasKey("TrilhaAprendizagemId");

                    b.ToTable("trilha_aprendizagem", (string)null);

                    b.HasData(
                        new
                        {
                            TrilhaAprendizagemId = 1,
                            CargaHoraria = 40,
                            Descricao = "Trilha voltada para iniciantes aprenderem lógica, algoritmos e fundamentos da programação.",
                            Titulo = "Introdução à Programação"
                        },
                        new
                        {
                            TrilhaAprendizagemId = 2,
                            CargaHoraria = 60,
                            Descricao = "Aprenda HTML, CSS, JavaScript e frameworks modernos para criação de interfaces.",
                            Titulo = "Desenvolvimento Web Front-end"
                        },
                        new
                        {
                            TrilhaAprendizagemId = 3,
                            CargaHoraria = 80,
                            Descricao = "Fundamentos de análise de dados, estatística básica e uso de Python em data science.",
                            Titulo = "Data Science para Iniciantes"
                        },
                        new
                        {
                            TrilhaAprendizagemId = 4,
                            CargaHoraria = 30,
                            Descricao = "Conceitos de Scrum, Kanban, ciclos ágeis e práticas de gestão moderna.",
                            Titulo = "Gestão de Projetos com Metodologias Ágeis"
                        },
                        new
                        {
                            TrilhaAprendizagemId = 5,
                            CargaHoraria = 50,
                            Descricao = "Especialização em redes sociais, tráfego pago, SEO e estratégias de conteúdo.",
                            Titulo = "Marketing Digital"
                        },
                        new
                        {
                            TrilhaAprendizagemId = 6,
                            CargaHoraria = 45,
                            Descricao = "Princípios de segurança digital, prevenção de ataques e boas práticas de proteção.",
                            Titulo = "Cibersegurança Essencial"
                        },
                        new
                        {
                            TrilhaAprendizagemId = 7,
                            CargaHoraria = 25,
                            Descricao = "Desenvolvimento de habilidades comportamentais como comunicação, trabalho em equipe e liderança.",
                            Titulo = "Soft Skills para o Mercado de Trabalho"
                        },
                        new
                        {
                            TrilhaAprendizagemId = 8,
                            CargaHoraria = 60,
                            Descricao = "Foco em vocabulário corporativo, reuniões, apresentações e comunicação profissional.",
                            Titulo = "Inglês para Negócios"
                        });
                });

            modelBuilder.Entity("GS2_Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataRedefinirSenha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_redefinir_senha");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(345)
                        .HasColumnType("character varying(345)")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)")
                        .HasColumnName("senha");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_usuario_id");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_email");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_login");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Ativo = true,
                            Cpf = "123.453.456-78",
                            DataCadastro = new DateTime(2025, 11, 21, 3, 0, 0, 0, DateTimeKind.Utc),
                            Email = "adm@adm.com",
                            Login = "administrador",
                            Nome = "ADM",
                            SenhaHash = "$2a$11$kfA7gVkje5eIJ5X0QlmUnOn9p24J2H3H16LLZGOx.t4vMyUStJmIu",
                            Telefone = "(11) 11111-1111",
                            TipoUsuarioId = 1
                        });
                });

            modelBuilder.Entity("GS2_Domain.Entities.Conteudo", b =>
                {
                    b.HasOne("GS2_Domain.Entities.Curso", "Curso")
                        .WithMany("Conteudos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conteudo_curso");

                    b.HasOne("GS2_Domain.Entities.TipoConteudo", "TipoConteudo")
                        .WithMany("Conteudos")
                        .HasForeignKey("TipoConteudoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conteudo_tipo");

                    b.Navigation("Curso");

                    b.Navigation("TipoConteudo");
                });

            modelBuilder.Entity("GS2_Domain.Entities.Curso", b =>
                {
                    b.HasOne("GS2_Domain.Entities.Nivel", "Nivel")
                        .WithMany("Cursos")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_curso_nivel");

                    b.HasOne("GS2_Domain.Entities.Usuario", "Proprietario")
                        .WithMany("CursosCriados")
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cursos_proprietario");

                    b.HasOne("GS2_Domain.Entities.TrilhaAprendizagem", "TrilhaAprendizagem")
                        .WithMany("Cursos")
                        .HasForeignKey("TrilhaAprendizagemId")
                        .HasConstraintName("fk_cursos_trilha");

                    b.Navigation("Nivel");

                    b.Navigation("Proprietario");

                    b.Navigation("TrilhaAprendizagem");
                });

            modelBuilder.Entity("GS2_Domain.Entities.CursoPalavraChave", b =>
                {
                    b.HasOne("GS2_Domain.Entities.Curso", "Curso")
                        .WithMany("CursosPalavrasChave")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cursopalavra_curso");

                    b.HasOne("GS2_Domain.Entities.PalavrasChaves", "PalavraChave")
                        .WithMany("CursosPalavrasChave")
                        .HasForeignKey("PalavraChaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cursopalavra_palavra");

                    b.Navigation("Curso");

                    b.Navigation("PalavraChave");
                });

            modelBuilder.Entity("GS2_Domain.Entities.MeusCursos", b =>
                {
                    b.HasOne("GS2_Domain.Entities.Curso", "Curso")
                        .WithMany("MeusCursos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meuscursos_curso");

                    b.HasOne("GS2_Domain.Entities.Usuario", "Usuario")
                        .WithMany("MeusCursos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meuscursos_usuario");

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GS2_Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("GS2_Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_refresh_tokens");
                });

            modelBuilder.Entity("GS2_Domain.Entities.Usuario", b =>
                {
                    b.HasOne("GS2_Domain.Entities.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_tipo_usuario");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("GS2_Domain.Entities.Curso", b =>
                {
                    b.Navigation("Conteudos");

                    b.Navigation("CursosPalavrasChave");

                    b.Navigation("MeusCursos");
                });

            modelBuilder.Entity("GS2_Domain.Entities.Nivel", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("GS2_Domain.Entities.PalavrasChaves", b =>
                {
                    b.Navigation("CursosPalavrasChave");
                });

            modelBuilder.Entity("GS2_Domain.Entities.TipoConteudo", b =>
                {
                    b.Navigation("Conteudos");
                });

            modelBuilder.Entity("GS2_Domain.Entities.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GS2_Domain.Entities.TrilhaAprendizagem", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("GS2_Domain.Entities.Usuario", b =>
                {
                    b.Navigation("CursosCriados");

                    b.Navigation("MeusCursos");
                });
#pragma warning restore 612, 618
        }
    }
}
